'''
This file was used to copy/paste code generated by the OpenAI whisper -> completion model program found in the local_python directory. Current code does not work :(
'''

import rclpy
from rclpy.node import Node
from control_msgs.action import FollowJointTrajectory
from std_msgs.msg import Int32MultiArray
from std_srvs.srv import Trigger
from action_msgs.msg import GoalStatus
from primitives.robot_primitives import RobotMoveClient, GripperControlPublisher, CurrentPoseService

class FigureEightDemo(Node):
    def __init__(self):
        super().__init__('figure_eight_demo')
        self.robot_move_client = RobotMoveClient(self, '/simulated_arm_server_1/follow_joint_trajectory')
        self.current_pose_service = CurrentPoseService(self, '/simulated_arm_server1/get_current_pose')

    def execute_figure_eight(self):
        # Define the figure eight trajectory in joint angles
        # Assuming an arbitrary trajectory that represents a figure eight
        figure_eight_trajectory = [
            [0.0, 0.1, 0.2, -0.1, -0.2, 0.0],
            [0.1, 0.0, 0.1, 0.1, 0.0, 0.1],
            [-0.1, 0.1, 0.0, -0.1, 0.2, -0.2],
            [0.0, -0.1, 0.2, 0.0, -0.2, 0.1],
            # Add more points to complete a figure eight
        ]

        # Move along the trajectory
        for point in figure_eight_trajectory:
            success = self.robot_move_client.move_to_joint_positions(point)
            if not success:
                self.get_logger().error("Failed to execute movement step in figure eight")
                return

def main(args=None):
    rclpy.init(args=args)
    node = FigureEightDemo()
    try:
        node.execute_figure_eight()
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()